### ISSUE TITLE
여행 생성관련 기능 변경

### ISSUE THREAD

**Issue by hyunmuam** [Team-Talking-Potatoes/WeGo_BE#42]
## ✍ Description

API 스펙 변경에 따른 약간의 수정이 필요합니다.

## Todo

- [x] Entity(`Travel`) 수정
- [x] Service계층 코드 수정
- [x] Request DTO 수정
