### ISSUE TITLE
추가 기능 구현(여행취소, 동행 참여 취소)

### ISSUE THREAD

**Issue by jickDo** [Team-Talking-Potatoes/WeGo_BE#67]
## ✍ Description

1차적인 기능 구현 이후 필요해진 api에 대한 프론트측 요청사항에 대한 기능 구현

## Todo

- [x] 여행취소 (여행 작성자가 삭제)
- [x] 동행취소 (여행 참여자가 취소)
- [x] 동행참여 (여행 참여)
