### ISSUE TITLE
모임 관련 API 마이그레이션

### ISSUE THREAD

**Issue by jickDo** [Team-Talking-Potatoes/WeGo_BE#7]
## ✍ Description

기존에 존재하던 모임 API 를 TTP 서버 환경에 맞는 환경으로 마이그레이션 하는 작업

## Todo

- [x] 모임 목록 조회
- [x] 모임 생성
- [x] 모임 상세 조회
- [x] 특정 모임의 참가자 목록 조회
- [x] 모임 취소
- [x] 모임 참여
- [x] 모임 참여 취소
